### ISSUE TITLE
`oraid status` is slow

### ISSUE THREAD

**Issue by albttx** [oraichain/orai#27]
Hello,

I noticed that `oraid status` is really slow compared to my other chains, any idea why ?

i'm doing often commands like

```bash
watch -n 0.5 oraid status
```

to check when catching up, but on orai, there is a real "lag" to get infos

**Comment by lehieuhust** [comment]
hello @albttx , I use this cmd  `watch -n 0.5 oraid status` and the orai chain's status change every 6 second. Could you please show me the app.toml, config.toml config and the log file

**Comment by albttx** [comment]
@lehieuhust my issue is about the time of printing output from `oraid status`

See a quick comparaison with Juno and Stargaze.
```
$ time oraid status
[...]
real    0m2.726s
user    0m2.684s
sys     0m0.068s

$ time junod status
[...]
real    0m0.112s
user    0m0.042s
sys     0m0.018s

$ time starsd status
[...]
real    0m0.107s
user    0m0.079s
sys     0m0.039s
```

The issue must come from `oraid` cli, because the rpc endpoint on `/status` is fast

```
$ curl localhost:26657/status
[...]
real    0m0.008s
user    0m0.000s
sys     0m0.006s
```

**Comment by lehieuhust** [comment]
I think you should use this cmd: `oraid status --node tcp://localhost:26657`

**Comment by albttx** [comment]
```
$ time oraid status --node tcp://localhost:26657
[...]
real    0m3.331s
user    0m3.273s
sys     0m0.081s
```

**Comment by lehieuhust** [comment]
> `--node tcp://localhost:26657` is already a default...
> 
> ```
> $ time oraid status --node tcp://localhost:26657
> [...]
> real    0m3.331s
> user    0m3.273s
> sys     0m0.081s
> ```

Could you please check if oraid process is running?

**Comment by albttx** [comment]
@lehieuhust  yes it is! it wouldn't respond me in the other case...

It's really come from `oraid` binary, because if i use `junod` binary it's faster (even with a remote rpc)

```
$ time junod status --node https://orai-rpc.nysa.network:443
[...]
real 0.07s
user 0.04s
```

**Comment by ducphamle2** [comment]
it's because we are using a compressed version of oraid when building it (with the flag -w -s), so it is slower, but smaller in size
