### ISSUE TITLE
A node startup error occurs

### ISSUE THREAD

**Issue by blocknodehub** [oraichain/orai#29]
v0.41.2
I used this downloaded snapshot (https://orai-singapore.s3.ap-southeast-1.amazonaws.com/mainnet_statesync_data_9149946_wasm_at_9149946_v0410.t ar.gz), but an error was reported when starting the node
<img width="1228" alt="截屏2023-04-13 17 30 07" src="https://user-images.githubusercontent.com/100512407/231717412-951c8a22-efec-4c3c-bfb2-8c656042fdaf.png">

**Comment by blocknodehub** [comment]
After compiling the 0.41.0 version and starting with snapshot, I stopped the node, and then started with 0.41.2. It could start, but I could not connect to the peer, the node could not synchronize data. I have been in the configuration file is configured with seeds = "31 e98a167492fd4c92c582cee5fd6fcd8ad59 @ d0f2d042405abbcac5193206642e1456fe89963@3.134.19.98:26656246 1 62.55.253.58:26656, bf083c57ed53a53ccd31dc160d69063c73b340e9@3.17.175.62:26656, 35 c1f999d67de56736b412a1325370a8e2fdb34a @ 5 189.169.99:26656, 5 ad3b29bf56b9ba95c67f282aa281b6f0903e921@64.225.53.108:26656, d091cabe3584cb32043cc0c9199b0c7a5b68ddcb @ seed.orai.synergynodes.com:26656"

**Comment by ducphamle2** [comment]
The snapshot is currently outdated. We'll update it asap so you can download the latest version.
