### ISSUE TITLE
Go dependencies step

### ISSUE THREAD

**Issue by Kwaskoff** [oraichain/orai#30]
On Go dependencies step (go get ./...) I have these errors:

```
go: downloading nhooyr.io/websocket v1.8.6
go: downloading github.com/Workiva/go-datastructures v1.0.53
/media/ex/go/pkg/mod/github.com/oraichain/wasmd@v0.30.1/x/wasm/keeper/testdata/reflect.go:4:2: package embed is not in GOROOT (/usr/lib/go-1.15/src/embed)
/media/ex/go/pkg/mod/golang.org/x/net@v0.4.0/http2/transport.go:19:2: package io/fs is not in GOROOT (/usr/lib/go-1.15/src/io/fs)
```

what's problem?

debian 11, go1.15.15 linux/arm64

**Comment by ducphamle2** [comment]
which branch are you working on right now?
normally you would just need to use `go mod tidy` to download and clean related dependencies. You should not add additional files manually
