### ISSUE TITLE
commission can't be lower than 3%: unauthorized

### ISSUE THREAD

**Issue by Jackwumingjie** [oraichain/orai#37]
I want to build the orai node with docker, use the snapshot(https://orai-singapore.s3.ap-southeast-1.amazonaws.com/mainnet_statesync_data_9077207_wasm_at_9149946_v0410.tar.gz) to sync, but the node can't run as the picture:
<img width="1126" alt="image" src="https://github.com/oraichain/orai/assets/39093109/da6719e6-c436-4d85-b8ca-568022991801">

**Comment by ducphamle2** [comment]
this snapshot is outdated now as fas as I'm concerned
