### ISSUE TITLE
Reporting a security bug

### ISSUE THREAD

**Issue by jessysaurusrex** [oraichain/orai#47]
Hi Oraichain!

I believe I may have found a security bug, but I cannot find contact information for sharing the details with you. Could a member of your team please contact me at security@interchain.io?

**Comment by ducphamle2** [comment]
> Hi Oraichain!
> 
> I believe I may have found a security bug, but I cannot find contact information for sharing the details with you. Could a member of your team please contact me at [security@interchain.io](mailto:security@interchain.io)?

Sure thing. Thanks for sharing the information!
